import { Directive, Field, ID, ObjectType } from '@nestjs/graphql';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import mongoose, { Document } from 'mongoose';
import { Comment } from 'src/comment/comment.model';

@Schema()
@ObjectType()
@Directive('@key(fields: "_id")')
export class File {
  @Field(() => ID)
  _id: mongoose.Schema.Types.ObjectId;

  // File's UUID is generated by the s3 viewer plugin. It is stored in the S3 object's metadata.
  // UUID is too long to put in MongoDB's _id field, so we store it in a separate field.
  @Prop()
  @Field()
  fileId: string;

  @Prop()
  @Field()
  bucket: string;

  @Prop({ type: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Comment' }], default: [] })
  @Field(() => [Comment], { nullable: true })
  comments: mongoose.Schema.Types.ObjectId[];
}

export type FileDocument = File & Document;
export const FileSchema = SchemaFactory.createForClass(File);
