version: '2'
services:
  jupyterhub:
    name: nist-jupyterhub-prod
    image: hicsail/nist-jupyterhub:main
    ports: ["8000:8000"]
    env_file:
      - ../../../stack.env
    volumes:
      - nist-jupyterhub-prod

volumes:
  nist-jupyterhub-prod:
    external: true
