version: '2'
services:
  nist-jupyterhub-prod:
    container_name: nist-jupyterhub-prod
    image: hicsail/nist-jupyterhub:main
    ports: ["8000:8000"]
    env_file:
      - ../../../stack.env
    volumes:
      - nist-jupyterhub-prod:/srv/jupyterhub
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jupyterhub-prod

volumes:
  nist-jupyterhub-prod:
    external: true

networks:
  jupyterhub-prod:
    external: true
